name: Horizons
description: Horizons template for Jekyll
paginate: 10
paginate_path: blog/page:num

assets:
  digest: true
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/js

collections:
  gallery:
    output: true
    permalink: /gallery/:slug/

exclude:
  - bin/*
  - photos/*
  - Gemfile
  - Gemfile.lock
  - README.md
  - design/
  - vendor/

gems:
  - jekyll-paginate
  - jekyll-assets
