name: Horizons
description: Horizons template for Jekyll
paginate: 10

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

collections:
  gallery:
    output: true
    permalink: /gallery/:slug/

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - photos/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

gems:
  - jekyll-paginate
  - jekyll-assets
